### ISSUE TITLE
_tag helpers

### ISSUE THREAD

**Issue by rurounijones** [stouset/twitter_bootstrap_form_for#33] opened 2011-12-20 00:57 UTC
I have noticed that a lot of the _tag helpers do not create the labels. For example `f.text_field :text` will create all the html markup for a twitter bootstrap label but `text_field_tag :text` will not.

From a POLS perspective I think the _tag helpers should behave as close as possible to their non_tag counterparts.

**Comment by stouset** [comment] 2011-12-20 16:39
Duplicate of #19.

**Closed as completed by stouset** 2011-12-20 16:39 UTC
