### ISSUE TITLE
Consider making a twitter_bootstrap_form version

### ISSUE THREAD

**Issue by danpersa** [stouset/twitter_bootstrap_form_for#11] opened 2011-10-19 17:56 UTC
The current version of _twitter_bootstrap_form_for_ works with objects.
Consider making a version of the method (maybe named _twitter_bootstrap_form_) that just generates the form.

As an example, I have the following form, and I'd like to use _twitter_bootstrap_form_ for it

``` erb
<%= form_tag({:controller => :reminders,  :action => :create}, {:remote => remote?, :class => "generic_form", :id => "new_reminder"}) do %>
  <%= render 'shared/error_messages', :object => @reminder %>
  <fieldset>
    <%= hidden_field :idea, :id %>
    <legend>Remind me to</legend>
    <ol>
      <li>
        <span class="title"><%= @idea.content %></span>
      </li>  
      <li>
        <%= label_tag :reminder_reminder_date, "on" %>
        <%= text_field :reminder, :reminder_date, :placeholder => "Reminder date" %>
        <%= errors_for_field(@reminder, :reminder_date) %>
      </li>
      <li>
        <%= label_tag :reminder_privacy_id, "as" %>
        <%= collection_select(:reminder, :privacy_id, Privacy.all, :id, :name) %>
      </li>
  </ol>
  </fieldset>
  <% unless hide_buttons? %>
  <fieldset>
    <%= submit_tag submit_button_name %>
  </fieldset>
  <% end %>
<% end %>
```

**Comment by stouset** [comment] 2011-10-19 19:04
The Twitter Bootstrap `FormBuilder` requires complete control over the generation of your form in order for it to be correctly marked up and styled. For instance, there would be no possible API I could expose that would turn that form (with `<ol>`'d form elements) into one compatible with Twitter Bootstrap's CSS.

The general markup of Twitter Bootstrap compatible forms is:

``` html
<form>
  <fieldset>
    <legend>Sign up</legend>
    <div class="clearfix">
      <label for="user_name">Name</label>
      <div class="input">
        <input id="user_name" name="user[name]"/>
      </div>
    </div>
    <div class="clearfix error">
      <label for="user_email">Email</label>
      <div class="input">
        <input id="user_email" name="user[email]"/>
        <span class='help-inline'>must be provided</span>
        <span class='help-block'>We won't <em>ever</em> share your email address.</span>
      </div>
    </div>
  </fieldset>
  <div class="actions">
    <input class="btn primary" name="commit" type="submit" value="Sign Up" />
  </div>
</form>
```

As you can see, it's completely different from your provided markup. There's simply no way to reconcile the two.

**Comment by stouset** [comment] 2011-10-19 19:05
What's stopping you from converting your existing form to the `twitter_bootstrap_form_for` `FormBuilder` syntax?

**Comment by danpersa** [comment] 2011-10-20 06:51
Nothing stops me from converting the code manually, but I want the syntax to be automatically generated (I think that's the whole idea behind _twitter_bootstrap_form_for_

I want to write something like this, and all the html markup to be generated automatically. The only main difference between this form and the actual form is that I don't use a model object...

``` erb
<%= twitter_bootstrap_form({:controller => :reminders,  :action => :create}, {:remote => remote?, :class => "generic_form", :id => "new_reminder"}) do |f| %>
    <span class="title"><%= @idea.content %></span>
    <%= f.inputs 'Remind me to' do %>
      <%= f.hidden_field :idea, :id %>
      <%= f.text_field :reminder, :reminder_date, :placeholder => "Reminder date" %>
      <%= f.collection_select(:reminder, :privacy_id, Privacy.all, :id, :name) %>
    <% end %>
    <% unless hide_buttons? %>
      <%= f.actions do %>
        <%= submit_tag submit_button_name %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

```

**Comment by danpersa** [comment] 2011-10-20 07:07
The idea is that if the twitter bootstrap markup ever modifies, and I have too many manually written forms in my application, I have to modify each of them. If the markup is encapsulated in the twitter_bootstrap_form_for gem, I only have to update the gem.

**Comment by stouset** [comment] 2011-10-20 13:24
I can look into it, but why not just make it use a model? That form could be generated with

``` erb
<%= twitter_bootstrap_form_for @reminder, :remote => remote? do |reminder| %>
  <span class="title"><%= @idea.content %></span>
  <%= reminder.inputs 'Remind me to' do %>
    <%= fields_for @idea do |idea| %>
      <%= idea.hidden_field :id %>
    <% end %>
    <%= reminder.text_field :reminder_date, :placeholder => 'Reminder date' %>
    <%= reminder.collection_select :privacy_id, 'Privacy', Privacy.all, :id, :name %>
  <% end %>
  <% unless hide_buttons? %>
    <%= reminder.actions do %>
      <%= reminder.submit submit_button_name %>
    <% end %>
  <% end %>
<% end %>
```

I'm not necessarily opposed to doing this, but the example can be trivially rewritten to use the existing syntax. I'd prefer not to write and maintain a completely independent `FormBuilder` if the existing one can handle the uses you're looking for. Especially since most forms _should_ be written with `form_for` syntax.

**Comment by danpersa** [comment] 2011-10-20 13:41
I'll try to rewrite my form as you suggested

**Comment by stouset** [comment] 2011-10-20 14:34
Closing this for now. Please let me know if you encounter something else that requires you use it without an object and we'll work something out.

**Closed as completed by stouset** 2011-10-20 14:34 UTC

**Comment by danpersa** [comment] 2011-10-20 15:22
Can you generate a collection_select?
When I try:

``` erb
<%= reminder.collection_select :privacy_id, 'Privacy', Privacy.all, :id, :name %>
```

I get

```
undefined method `map' for :id:Symbol
```

the last lines from the stacktrace are:

```
actionpack (3.1.1) lib/action_view/helpers/form_options_helper.rb:339:in `options_from_collection_for_select'
actionpack (3.1.1) lib/action_view/helpers/form_options_helper.rb:570:in `to_collection_select_tag'
actionpack (3.1.1) lib/action_view/helpers/form_options_helper.rb:166:in `collection_select'
actionpack (3.1.1) lib/action_view/helpers/form_options_helper.rb:614:in `collection_select'
/home/dix/.bundler/ruby/1.9.1/twitter_bootstrap_form_for-c74cb032486e/lib/twitter_bootstrap_form_for/form_builder.rb:84:in `block (4 levels) in <class:FormBuilder>'
actionpack (3.1.1) lib/action_view/helpers/capture_helper.rb:40:in `block in capture'
actionpack (3.1.1) lib/action_view/helpers/capture_helper.rb:187:in `with_output_buffer'
```

**Comment by stouset** [comment] 2011-10-20 16:00
That should work. I'll check to see why it doesn't over lunch or this evening.

**Comment by stouset** [comment] 2011-10-22 20:12
Works for me. What version are you using?

``` bash
$ bundle show twitter_bootstrap_form_for
```

**Comment by danpersa** [comment] 2011-10-26 18:40
/home/dix/.rvm/gems/ruby-1.9.2-p290@remindmetolive/bundler/gems/twitter_bootstrap_form_for-c74cb032486e

**Comment by stouset** [comment] 2011-10-26 18:49
I just tested against that version explicitly, and it works without issue. I adapted a dummy test case to my own `User` module:

``` haml
= twitter_bootstrap_form_for @user do |user|
  = user.inputs do
    = user.collection_select :id, 'User ID', User.all, :id, :name
```

Can you provide more details?

**Comment by danpersa** [comment] 2011-10-26 18:51
I'm using rails 3.1.1... do you use the same version of rails?

**Comment by stouset** [comment] 2011-10-26 18:54
``` sh
$ cat Gemfile.lock
GIT
  remote: ../github.com/twitter_bootstrap_form_for
  revision: c74cb032486ed2bdce9fb2d51969c56a63b670de
  ref: c74cb032486e
  specs:
    twitter_bootstrap_form_for (1.0.1)
      rails (~> 3)

GEM
    ...
    rails (3.1.1)
      actionmailer (= 3.1.1)
      actionpack (= 3.1.1)
      activerecord (= 3.1.1)
      activeresource (= 3.1.1)
      activesupport (= 3.1.1)
      bundler (~> 1.0)
      railties (= 3.1.1)
    ...
```

**Comment by danpersa** [comment] 2011-10-26 18:57
here, <%= reminder.collection_select :privacy_id, 'Privacy', Privacy.all, :id, :name %>

your gem expects that the forth parameter (_:id_) which is a symbol, to have a _map_ method... you know the code better, maybe you can find out why the _map_ method...

**Comment by danpersa** [comment] 2011-10-26 19:05
if I use:

``` ruby
<%= reminder.collection_select :privacy_id, 'Privacy', 'XXX', Privacy.all, :id, :name %>
```

it generates me the next html code (with some duplication in it):

``` html
<div class=" clearfix" id="reminder_privacy_id_input">
    <label for="reminder_privacy_id">Privacy</label>
    <div class="input">
        <div class=" clearfix" id="reminder_privacy_id_input">
            <label for="reminder_privacy_id">XXX</label>
                <div class="input">
                    <select id="reminder_privacy_id" name="reminder[privacy_id]">
                         <option value="1">public</option>
                         <option value="2">private</option>
                    </select>
                </div>
        </div>
    </div>
</div>
```

maybe because my form is nested?

``` erb
<%= twitter_bootstrap_form_for @reminder, :remote => remote? do |reminder| %>
  <span class="title"><%= @idea.content %></span>
  <%= reminder.inputs 'Remind me to' do %>
    <%= fields_for @idea do |idea| %>
      <%= idea.hidden_field :id %>
    <% end %>
    <%= reminder.text_field :reminder_date, :placeholder => 'Reminder date' %>

    <%= reminder.collection_select :privacy_id, 'Privacy', 'XXX', Privacy.all, :id, :name %>

  <% end %>
  <% unless hide_buttons? %>
    <%= reminder.actions do %>
      <%= reminder.submit submit_button_name %>
    <% end %>
  <% end %>
<% end %>
```

**Comment by stouset** [comment] 2011-10-26 19:16
Actually, all I do (in this scenario) is strip the attribute (`:privacy_id`) and the label (`Privacy`) off the front, and pass the attribute and remaining parameters to Rails' form helpers.

There's something weird going on in your example. My testing outputs

``` html
<fieldset>
  <div class="clearfix" id="user_id_input">
    <label for="user_id">Privacy</label>
    <div class="input">
      <select id="user_id" name="user[id]">
        ...
      </select>
    </div>
  </div>
  ...
</fieldset>
```

It may be the `fields_for` that's somehow throwing a wrench in the works. Can you take it out really quick and see if that fixes the problem?

**Comment by stouset** [comment] 2011-10-26 19:30
Can you also quickly force the gem to be at version 1.0.1, just to make sure?

`gem :twitter_bootstrap_form_for, '1.0.1'`

**Comment by danpersa** [comment] 2011-10-26 19:36
My form is now:

``` ruby
<%= twitter_bootstrap_form_for @reminder do |reminder| %>
    <%= reminder.inputs 'Remind me to' do %>
        <%= reminder.text_field :reminder_date, :placeholder => 'Reminder date' %>
        <%= reminder.collection_select :privacy_id, 'Privacy', 'XXX', Privacy.all, :id, :name %>
    <% end %>
    <%= reminder.actions do %>
        <%= reminder.submit submit_button_name %>
    <% end %>
<% end %>
```

the html:

``` html
 <form accept-charset="UTF-8" action="/reminders" class="new_reminder" id="new_reminder" method="post">
<div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;" />
<input name="authenticity_token" type="hidden" value="ah2Mn8PKiZHHn2OorhNPbZVuSAhnYHwGFZVp97RgJgY=" /></div>
    <fieldset><legend>Remind me to</legend>
        <div class=" clearfix" id="reminder_reminder_date_input"><label for="reminder_reminder_date">Reminder date</label><div class="input"><input id="reminder_reminder_date" name="reminder[reminder_date]" placeholder="Reminder date" size="30" type="text" /></div></div>

        <div class=" clearfix" id="reminder_privacy_id_input"><label for="reminder_privacy_id">Privacy</label><div class="input"><div class=" clearfix" id="reminder_privacy_id_input"><label for="reminder_privacy_id">XXX</label><div class="input"><select id="reminder_privacy_id" name="reminder[privacy_id]"><option value="1">public</option>
<option value="2">private</option></select></div></div></div></div>

</fieldset>
    <div class="actions">
        <input class="btn primary" name="commit" type="submit" value="Create reminder" />
</div>
</form>
```

if I delete the third parameter ('XXX') I get the  
`undefined method `map' for :id:Symbol`

**Comment by danpersa** [comment] 2011-10-26 19:40
I fixed it... I had the 

```
gem "dynamic_form"
gem "simple_form"
```

in my Gemfile...

sorry for the trouble...

**Comment by danpersa** [comment] 2011-10-26 19:40
keep up the good work!

**Comment by stouset** [comment] 2011-10-26 19:41
What was the conflict?

**Comment by danpersa** [comment] 2011-10-26 19:42
I think one of the gems was overriding one of the default rails helpers...

**Comment by stouset** [comment] 2011-10-26 19:43
Gotcha. Glad you figured that out... I thought I might be going crazy.

Please let me know anything else I can help with.

**Comment by danpersa** [comment] 2011-10-26 19:45
I was going crazy too :)) I took a two days break and seems that today was my lucky day :D

**Comment by derekprior** [comment] 2011-11-14 19:16
FYI, It seems to be simple_form that causes this. I was trying to convert from simple_form to t_b_f_f and came across the same issue.

**Comment by stouset** [comment] 2011-11-14 19:29
For what it's worth, this gem does _not_ override the provided Rails helpers. Everything is scoped to within the gem's subclassed `FormBuilder`. So if you ever want to move away from my gem, you don't have to deal with this type of vendor lock-in. :)

**Comment by stouset** [comment] 2011-11-14 20:36
I'll update the README later this afternoon to point here, so `simple_form` converts will know what the problem is.

Ideally, someone would submit a bug report to José at plataformatec and let him know about this. I did a simple check but couldn't see where the override was happening so haven't submitted a bug yet.

**Comment by derekprior** [comment] 2011-11-14 21:03
It happens here: https://github.com/plataformatec/simple_form/blob/v1.5/lib/simple_form/action_view_extensions/builder.rb#L169

Most of my rails form building has been with simple_form so I've never really called collection_select directly before. I'll try to figure out what exactly they changed.

**Comment by derekprior** [comment] 2011-11-14 22:15
Hmmm - I'm still getting this even after removing the simple_form gem, it's configuration, and the initializer. Maybe I'm just doing something stupid...

**Comment by derekprior** [comment] 2011-11-14 22:45
Ok, apologies for the confusion. I had the arguments to f.collection_select wrong, I think. The API docs specify:

```
collection_select(object, method, collection, value_method, text_method, options = {}, html_options = {}) public
```

I was under the impression that the first argument was not needed when using a form builder, so it would be:

```
f.collection_select(method, collection, value_method, text_method, options = {}, html_options = {}) public
```

Instead, it seems to be that I had to do:

```
= f.collection_select method, LABEL, collection, value_method, text_method
```

but I couldn't find that documentation anywhere. I'm not sure SimpleForm was at fault here. I think it was just my naivete.

**Comment by stouset** [comment] 2011-11-14 23:06
Ah! Sorry, that's the expected call signature for `collection_select` with this gem. Within the `FormBuilder`, all input elements have their second parameter become the label. This does need to be documented better, as it seems to be a source of confusion for others.

**Comment by stouset** [comment] 2011-11-15 13:14
Cleared this up in 5081057b4cf9ff72b8321d7d1e48a082ddc73e06
